index:
    path: /
    controller: App\Controller\HomeController::index

post.index: 
    path: /posts
    controller: App\Controller\PostController::index

post.create: 
    path: /posts/new
    controller: App\Controller\PostController::create
