app_login: 
    path: /login
    controller: App\Controller\SecurityController::login

app_register:
    path: /register
    controller: App\Controller\UserController:register

post.index: 
    path: /
    controller: App\Controller\PostController::index

post.create: 
    path: /posts/new
    controller: App\Controller\PostController::create
