app_login: 
    path: /login
    controller: App\Controller\SecurityController::login

app_register:
    path: /register
    controller: App\Controller\UserController::register

user.index: 
    path: /users
    controller: App\Controller\UserController::index

user.profile: 
    path: /profile/{id}
    controller: App\Controller\UserController::show

user.update: 
    path: /profile/edit/{id}
    controller: App\Controller\UserController::update

post.index: 
    path: /
    controller: App\Controller\PostController::index

post.create: 
    path: /posts/new
    controller: App\Controller\PostController::create
